### ISSUE TITLE
Member, add webcal/ical calendar feed

### ISSUE THREAD

**Issue by Alex77825** [csa-admin-org/csa-admin#134]
The Internet Calendaring and Scheduling Core Object Specification (iCalendar)  [ file type ".ics" ]
 
The idea is that the client can download an .ics file to import directly a Calendar, this new feature will be very nice.

Possible to add this? I think it would be great when the admin can import an .ics file, the file will populate the database and generate the Calendar in the CMS (Calendrier des livraisons), and then the user can download it to import it to the smartphone calendar or Thunderbird or Outlook. 

Thank's to read this future request 

have a nice day!

**Comment by thibaudgg** [comment]
Hi, thank you for your message.

Could you please be a bit more specific about which part of the application should expose an iCalendar feed? I'm a bit confused by your request. Is it about the members section or the admin?

**Comment by Alex77825** [comment]
It's about the members section, I would like a bouton to download an .ics file, for exemple here (see picture) 
![Capture d’écran du 2024-10-31 13-20-13](https://github.com/user-attachments/assets/536a43a9-dc71-4e74-8363-b7704c8df704).

My be you can add an function in the Admin too, to have the posibility to upload the .ics fille 

To resum an uploade in Admin and a download in members section.

(I am only a member so I don't now how look's the Admin interface^)

**Comment by thibaudgg** [comment]
Thanks for the details, that's more clear now. 👍🏻 

Adding an iCal feed for each member's deliveries makes sense, I will add that feature to the list.

On the admin's side, this isn't much needed as the platform offer advanced form to batch create deliveries.

**Comment by thibaudgg** [comment]
Hey @Alex77825,

I have added a new webcal/ical calendar feed in the member section, which includes all the basket deliveries and activity participations (when this feature is used by the organization).

Please let me know if that fulfil your need!

You can subscribe to it from here:

![Image](https://github.com/user-attachments/assets/52548726-d452-4ccc-a061-b723aaa74cf2)

**Comment by thibaudgg** [comment]
Temps: ~8h
